apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-helm
  labels:
    app: grafana-helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana-helm
  template:
    metadata:
      labels:
        app: grafana-helm
    spec:
      containers:
      - name: grafana-helm
        image: grafana/grafana
        ports:
        - containerPort: 3000