kind: Service
apiVersion: v1
metadata:
  name: grafana-helm
spec:
  ports:
    - port: 30007 # The port on the Service to expose
      targetPort: 3000 # The port on the destination pod to bind to
      nodePort: 30007 # The port the Service will listen to at the Node level
      protocol: TCP 
  selector:
    app: grafana-helm # As specified on the pod-definition
  type: NodePort # The type of Service this service is (as opposed to ClusterIP, Load Balancer, etc)